spring:
  application:
    name: salessimulator
  datasource:
    url: jdbc:mysql://localhost:3306/fee-db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: example
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update